version = 1

exclude_patterns = [
    "public/app-assets/**",
    "public/assets/**",
    "tmp/**",
    "bin/**"
]

test_patterns = [
    "tests/**"
]

[[analyzers]]
name = "ruby"
enabled = true

[[analyzers]]
name = "javascript"
enabled = true